### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marie-eveboulanger** [a-dumont/Thermal_Conductivity#5]
We need to have something ''clef en main'' so people could use this code easily. 

Have a look at [pdoc](https://pdoc3.github.io/pdoc/doc/pdoc/#gsc.tab=0).

Any other ideas are also welcome 😃.

**Comment by a-dumont** [comment]
I've already started writing the [wiki](https://github.com/a-dumont/Thermal_Conductivity/wiki)

**Comment by marie-eveboulanger** [comment]
Je viens de voir, c'est un bon début. Cela m'a aidé à le rouler.
