### ISSUE TITLE
Make a class to read file

### ISSUE THREAD

**Issue by marie-eveboulanger** [a-dumont/Thermal_Conductivity#7]
It could increase readability and ease future maintenance if the `__read_file` method of the `Conductivity` class create a new object to do the analysis. Something like

```python
class Conductivity:
    ...
    def __read_data_from(self, filename):
        data = DataReader(filename).read_data()
        self.__set_data_from(data)
``` 

And in some other file

```python
class DataReader:
    ...
    def read_data(self, filename):
        ...
``` 

A little bit like the `SampleDimensions` class.

What do you think ?

**Comment by a-dumont** [comment]
The problem with that is that I try to keep every bit of the code self contained. That way if we ever want to expand the code to also include tools for something like seebeck measurements we do not have to deal with multiple readfile classes

**Comment by marie-eveboulanger** [comment]
The goal is to keep the code modular. Let's take your example and you want to add a Seebeck functionality, most of the implementation should be similar. Therefore, in the ReadData class, you could simply add a method like this :

```python
class DataReader:
    ...
    def read_data(self):
        ...
    def read_data_for_seebeck(self):
       data = self.read_data()
       return self.seebeck_stuff(data)
``` 

and then you can call that in the conductivity class.
